### PR TITLE
Allow users to alter layer display order with drag and drop

### PR DESCRIPTION
**Pull request by bhickson**
Allows users to drag an drop previewed layers to change their display order (top on top).  Does so by giving each layer in the search results an id for its div that is based off the solr id field.  This ID field is then used to set zIndex value when in the previewed layers listing. Utilizes existing zIndexChange function in map div.

### CODE REVIEW

**Comment by bhickson** [comment]
How about passing the layer id as a custom HTML5 attribute?  e.g.
instead of
    id : function() {return this.model.get("layerid") },
we use
    attributes: function() { return { "layerid" : this.model.get("layerid)
} },

Then in the setSortableLayers function we can use call it using the
attribute "layerid," which is even more explicit. Seems to work in testing
with and without spaces.

**Comment by chrissbarnett** [comment]
Hi Ben, that works for me. I'll do a quick local test tomorrow, then, providing everything goes as expected, I'll accept your request.

**Comment by chrissbarnett** [comment]
Hi Ben, sorry, I don't see the changes you mentioned in your last comment in the pull request. Also, some other changes seem to have crept in.

**Comment by bhickson** [comment]
My bad. Closed pull request.  I'll recreate with only changes relevant to
layer sorting.

**Pull request closed without merging**
